version: '3.4'

services:
  botgildraen:
    image: botgildraen
    build:
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./dist/index.js"]
