version: "3.9"

services:
  app:
    image: node:18-slim
    container_name: app_bot
    working_dir: /usr/app
    user: node
    volumes:
      - ./:/usr/app
  aws:
    image: amazon/aws-cli:2.9.14
    container_name: aws
    env_file:
      - .env
