version: '3.9'
services:
  dev:
    build: .
    container_name: dev_bot
    working_dir: /usr/app
    volumes:
      - ../:/usr/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ../.env
